export function first() {
    const icons = [
        'img/Angular.png',
        'img/Bootstrap.png',
        'img/C.png',
        'img/CodeIgniter.png',
        'img/csharp.png',
        'img/CSS3.png',
        'img/Go.png',
        'img/HTML5.png',
        'img/Java.png',
        'img/JavaScript.png',
        'img/jQuery.png',
        'img/Laravel.png',
        'img/Next.js.png',
        'img/Node.js.png',
        'img/Nuxt JS.png',
        'img/PHP.png',
        'img/Python.png',
        'img/React.png',
        'img/Rust.png',
        'img/Svelte.png',
        'img/Swift.png',
        'img/Tailwind CSS.png',
    ];
}